# Generated by Django 3.1.7 on 2021-03-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=120)),
                ('fb_link', models.CharField(max_length=120)),
                ('insta_link', models.CharField(max_length=120)),
                ('photo', models.ImageField(null=True, upload_to='media/team/%Y/%m/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
