# Generated by Django 3.1.7 on 2021-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('fb_link', models.CharField(max_length=254)),
                ('youtube_link', models.CharField(max_length=254)),
                ('twitter_link', models.CharField(max_length=254)),
                ('instagram_link', models.CharField(max_length=254)),
            ],
        ),
    ]
